[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quap"
version = "0.3"
authors = [
  { name="Jordan M. R. Fox", email="jordanmrfox@gmail.com" },
]
description = "Modeling many-fermion systems"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/jmrfox/quap"